name: robotremoteserver_dart
description: Robot framework remote server
version: 0.0.3
homepage: https://github.com/binithb/robotremoteserver_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection:
  http:
  meta:
  xml:
  xml_rpc: 0.4.0

dev_dependencies:
  pedantic:
  test:
