name: robotremoteserver-dart
description: Robot framework remote server
# version: 0.0.1
# homepage: not yet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  meta: ^1.3.0
  xml: ^5.0.0
  xml_rpc: ^0.4.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
